language: node_js
node_js:
  - "12"
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: HRKU-74bf898c-978d-4ba2-be6b-c0b3ee3c6edc
  app: Devops-Travis-CI
  on:
    branch: main
