language: node_js
node_js:
- '12'
before_install:
- sudo apt-get update -y
- sudo apt-get install -y software-properties-common
- sudo add-apt-repository ppa:openjdk-r/ppa -y
- sudo apt-get update -y
- sudo apt-get install -y openjdk-17-jdk
- export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
- export PATH=$JAVA_HOME/bin:$PATH
- java -version
install:
- npm install
script:
- npm test
addons:
  sonarcloud:
    organization: udaydamerla5
    token:
      secure: tECTLNFTnXL/+nCpKq/jTabuyzUvdbRXhwLxIRJgk2Al0WE3cXHjD47qEO4X8A4ZkY9bZvPHliNNdqwqx+pfnden60lYLtSddqXYb0qwg99vT2JPgqNwln5G9/KLCJINaWl7McPOUC/x+FvX1bOEcumzZPvg7/Fng5thw0Oahrxm6TKOHSjcpmQh1BIf2po/5aQnF6KQ/l5CRDvcwkLru0lfxqRqk74yZh/EUstEtaLf3eVvxbWFJ0/sWeRGk492QwEE7rp2mWt7EfVzbV5iUG33sPiBvNkR1MjRCtNx9GOxup4/GpSidDXYO3TzZaBF4IWEJb9Z1uYi1vVTj7amdzzQOSGHW25w7VR2/zVn8z7o5Zc2G67oYiypqQ2W8JXmGCP94WDkcYiZL35lZych94uKoCTDOtvowdn/0hA+8FMFARzch462WBT/qXt0ghOdzNxzUTjEO43HJa3cFskxckGVYkkXQGWPugnYSHMRl1hNGcQqvmHr9bqbjOWtbaReM79CbhJzDt6PWeBR9AHCRRrlfbd29EpqRG6oLpwjnbtvTOlulBF9A0kbesEVic9cwP2XJtZSH9jt7jBFstScFTdV8SDuwkhP2ayceje49AMKzOsnhcj+7nicwbT6iPopvSqa+63yNV/nCR+mHUKkjUA+T4AdT+WP6/if/ypX4lE=
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: pqwMrw7h0lC8497hzRHON8Wj7v1aBqQQSt0ngbOWeOrvz3O0dXUEZsGBkGT8IxDTUIRPHmg24DwVASObBFyTHfl9ZSczb7fnGSQshHodimzPZSiOlEl2sSgF9OCPodMhC6WK2jR4j1Z2v6t9IVQBL6YUNMpVYc3BgHieGcKXd0Wk+Yvi0RcRxlRVJjtQ22JMcR8h/Dlc8pABCr/hG1vsDv96Sn7aec8Q7ZFl9ZQcK9Ge+XqpuwURT2Q3PD5f7N1pP18pM9D4Hkm7q2Jr46xjwOEsOw+YxkIxTZdbgrSwIDX/Yfkaud9AI1O3A0xIM/17640RQAwiU2ow/jl1zm1Q0gfCxxhlAkI8PfWDDaTYMN/TtTr1sbKRTdl+brxfvl2Fy2xTpMJUBEuD3wqTxpLugHL+kzT1SqEyrTrdciP79ROizomehiu2tNF3AT94K9QGfB/r2OgVnyfGDSDK1JiHu22mX4e5KujnhzjWpib1J90Bas3MKFuzR3PqZclyo91AtXmyzQbCCJyYEA4leeRTQZn0P78F/dlRJr+yHzoJeRcl8Is7YMluaxdHJDU7vyKpF/JR/Oz5GLRquXVvvWatJIa0+/hfo3z58hzOFn0uDFaDkz+cz+kDMS5x/SawUFdhzOajXnDeWY0s7MnAf/488/Nh3kO1pJ36cLKcpNPgOR8=
  app: devops-travis-ci
  on:
    branch: main
env:
  global:
  - secure: tECTLNFTnXL/+nCpKq/jTabuyzUvdbRXhwLxIRJgk2Al0WE3cXHjD47qEO4X8A4ZkY9bZvPHliNNdqwqx+pfnden60lYLtSddqXYb0qwg99vT2JPgqNwln5G9/KLCJINaWl7McPOUC/x+FvX1bOEcumzZPvg7/Fng5thw0Oahrxm6TKOHSjcpmQh1BIf2po/5aQnF6KQ/l5CRDvcwkLru0lfxqRqk74yZh/EUstEtaLf3eVvxbWFJ0/sWeRGk492QwEE7rp2mWt7EfVzbV5iUG33sPiBvNkR1MjRCtNx9GOxup4/GpSidDXYO3TzZaBF4IWEJb9Z1uYi1vVTj7amdzzQOSGHW25w7VR2/zVn8z7o5Zc2G67oYiypqQ2W8JXmGCP94WDkcYiZL35lZych94uKoCTDOtvowdn/0hA+8FMFARzch462WBT/qXt0ghOdzNxzUTjEO43HJa3cFskxckGVYkkXQGWPugnYSHMRl1hNGcQqvmHr9bqbjOWtbaReM79CbhJzDt6PWeBR9AHCRRrlfbd29EpqRG6oLpwjnbtvTOlulBF9A0kbesEVic9cwP2XJtZSH9jt7jBFstScFTdV8SDuwkhP2ayceje49AMKzOsnhcj+7nicwbT6iPopvSqa+63yNV/nCR+mHUKkjUA+T4AdT+WP6/if/ypX4lE=
