global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'python_app'
    static_configs:
      - targets: ['localhost:5000']
